/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PagedResponseRecipeDto,
  RecipeDto,
} from '../models/index';
import {
    PagedResponseRecipeDtoFromJSON,
    PagedResponseRecipeDtoToJSON,
    RecipeDtoFromJSON,
    RecipeDtoToJSON,
} from '../models/index';

export interface CreateRecipeRequest {
    recipeDto: Omit<RecipeDto, 'id'>;
}

export interface DeleteRecipeRequest {
    id: string;
}

export interface GetMyRecipesRequest {
    page?: number;
    size?: number;
    searchTitle?: string;
}

export interface GetRecipeByIdRequest {
    id: string;
}

export interface UpdateRecipeRequest {
    id: string;
    recipeDto: Omit<RecipeDto, 'id'>;
}

/**
 * 
 */
export class RecipeControllerApi extends runtime.BaseAPI {

    /**
     */
    async createRecipeRaw(requestParameters: CreateRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeDto>> {
        if (requestParameters['recipeDto'] == null) {
            throw new runtime.RequiredError(
                'recipeDto',
                'Required parameter "recipeDto" was null or undefined when calling createRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recipes`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecipeDtoToJSON(requestParameters['recipeDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeDtoFromJSON(jsonValue));
    }

    /**
     */
    async createRecipe(requestParameters: CreateRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeDto> {
        const response = await this.createRecipeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteRecipeRaw(requestParameters: DeleteRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recipes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteRecipe(requestParameters: DeleteRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteRecipeRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getMyRecipesRaw(requestParameters: GetMyRecipesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedResponseRecipeDto>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['searchTitle'] != null) {
            queryParameters['searchTitle'] = requestParameters['searchTitle'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recipes/my-recipes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedResponseRecipeDtoFromJSON(jsonValue));
    }

    /**
     */
    async getMyRecipes(requestParameters: GetMyRecipesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedResponseRecipeDto> {
        const response = await this.getMyRecipesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRecipeByIdRaw(requestParameters: GetRecipeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRecipeById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recipes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeDtoFromJSON(jsonValue));
    }

    /**
     */
    async getRecipeById(requestParameters: GetRecipeByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeDto> {
        const response = await this.getRecipeByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateRecipeRaw(requestParameters: UpdateRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecipeDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateRecipe().'
            );
        }

        if (requestParameters['recipeDto'] == null) {
            throw new runtime.RequiredError(
                'recipeDto',
                'Required parameter "recipeDto" was null or undefined when calling updateRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recipes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RecipeDtoToJSON(requestParameters['recipeDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecipeDtoFromJSON(jsonValue));
    }

    /**
     */
    async updateRecipe(requestParameters: UpdateRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecipeDto> {
        const response = await this.updateRecipeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
