/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackDto
 */
export interface FeedbackDto {
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    source?: string;
    /**
     * 
     * @type {number}
     * @memberof FeedbackDto
     */
    rating?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackDto
     */
    hadProblems?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeedbackDto
     */
    suggestions?: string;
}

/**
 * Check if a given object implements the FeedbackDto interface.
 */
export function instanceOfFeedbackDto(value: object): value is FeedbackDto {
    return true;
}

export function FeedbackDtoFromJSON(json: any): FeedbackDto {
    return FeedbackDtoFromJSONTyped(json, false);
}

export function FeedbackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'source': json['source'] == null ? undefined : json['source'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'hadProblems': json['hadProblems'] == null ? undefined : json['hadProblems'],
        'suggestions': json['suggestions'] == null ? undefined : json['suggestions'],
    };
}

export function FeedbackDtoToJSON(json: any): FeedbackDto {
    return FeedbackDtoToJSONTyped(json, false);
}

export function FeedbackDtoToJSONTyped(value?: FeedbackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': value['source'],
        'rating': value['rating'],
        'hadProblems': value['hadProblems'],
        'suggestions': value['suggestions'],
    };
}

