/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeDto } from './RecipeDto';
import {
    RecipeDtoFromJSON,
    RecipeDtoFromJSONTyped,
    RecipeDtoToJSON,
    RecipeDtoToJSONTyped,
} from './RecipeDto';

/**
 * 
 * @export
 * @interface PagedResponseRecipeDto
 */
export interface PagedResponseRecipeDto {
    /**
     * 
     * @type {Array<RecipeDto>}
     * @memberof PagedResponseRecipeDto
     */
    content?: Array<RecipeDto>;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseRecipeDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponseRecipeDto
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PagedResponseRecipeDto interface.
 */
export function instanceOfPagedResponseRecipeDto(value: object): value is PagedResponseRecipeDto {
    return true;
}

export function PagedResponseRecipeDtoFromJSON(json: any): PagedResponseRecipeDto {
    return PagedResponseRecipeDtoFromJSONTyped(json, false);
}

export function PagedResponseRecipeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponseRecipeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(RecipeDtoFromJSON)),
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PagedResponseRecipeDtoToJSON(json: any): PagedResponseRecipeDto {
    return PagedResponseRecipeDtoToJSONTyped(json, false);
}

export function PagedResponseRecipeDtoToJSONTyped(value?: PagedResponseRecipeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(RecipeDtoToJSON)),
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

