/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';
import type { PostDto } from './PostDto';
import {
    PostDtoFromJSON,
    PostDtoFromJSONTyped,
    PostDtoToJSON,
    PostDtoToJSONTyped,
} from './PostDto';

/**
 * 
 * @export
 * @interface PagePostDto
 */
export interface PagePostDto {
    /**
     * 
     * @type {number}
     * @memberof PagePostDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagePostDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PagePostDto
     */
    size?: number;
    /**
     * 
     * @type {Array<PostDto>}
     * @memberof PagePostDto
     */
    content?: Array<PostDto>;
    /**
     * 
     * @type {number}
     * @memberof PagePostDto
     */
    number?: number;
    /**
     * 
     * @type {Array<SortObject>}
     * @memberof PagePostDto
     */
    sort?: Array<SortObject>;
    /**
     * 
     * @type {boolean}
     * @memberof PagePostDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PagePostDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PagePostDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PagePostDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PagePostDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PagePostDto interface.
 */
export function instanceOfPagePostDto(value: object): value is PagePostDto {
    return true;
}

export function PagePostDtoFromJSON(json: any): PagePostDto {
    return PagePostDtoFromJSONTyped(json, false);
}

export function PagePostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagePostDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PostDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortObjectFromJSON)),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PagePostDtoToJSON(json: any): PagePostDto {
    return PagePostDtoToJSONTyped(json, false);
}

export function PagePostDtoToJSONTyped(value?: PagePostDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PostDtoToJSON)),
        'number': value['number'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortObjectToJSON)),
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

