/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { RecipeDto } from './RecipeDto';
import {
    RecipeDtoFromJSON,
    RecipeDtoFromJSONTyped,
    RecipeDtoToJSON,
    RecipeDtoToJSONTyped,
} from './RecipeDto';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageRecipeDto
 */
export interface PageRecipeDto {
    /**
     * 
     * @type {number}
     * @memberof PageRecipeDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRecipeDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageRecipeDto
     */
    size?: number;
    /**
     * 
     * @type {Array<RecipeDto>}
     * @memberof PageRecipeDto
     */
    content?: Array<RecipeDto>;
    /**
     * 
     * @type {number}
     * @memberof PageRecipeDto
     */
    number?: number;
    /**
     * 
     * @type {Array<SortObject>}
     * @memberof PageRecipeDto
     */
    sort?: Array<SortObject>;
    /**
     * 
     * @type {boolean}
     * @memberof PageRecipeDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageRecipeDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageRecipeDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageRecipeDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageRecipeDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageRecipeDto interface.
 */
export function instanceOfPageRecipeDto(value: object): value is PageRecipeDto {
    return true;
}

export function PageRecipeDtoFromJSON(json: any): PageRecipeDto {
    return PageRecipeDtoFromJSONTyped(json, false);
}

export function PageRecipeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageRecipeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(RecipeDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : ((json['sort'] as Array<any>).map(SortObjectFromJSON)),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageRecipeDtoToJSON(json: any): PageRecipeDto {
    return PageRecipeDtoToJSONTyped(json, false);
}

export function PageRecipeDtoToJSONTyped(value?: PageRecipeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(RecipeDtoToJSON)),
        'number': value['number'],
        'sort': value['sort'] == null ? undefined : ((value['sort'] as Array<any>).map(SortObjectToJSON)),
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

