/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostDto } from './PostDto';
import {
    PostDtoFromJSON,
    PostDtoFromJSONTyped,
    PostDtoToJSON,
    PostDtoToJSONTyped,
} from './PostDto';

/**
 * 
 * @export
 * @interface PagedResponsePostDto
 */
export interface PagedResponsePostDto {
    /**
     * 
     * @type {Array<PostDto>}
     * @memberof PagedResponsePostDto
     */
    content?: Array<PostDto>;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePostDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PagedResponsePostDto
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PagedResponsePostDto interface.
 */
export function instanceOfPagedResponsePostDto(value: object): value is PagedResponsePostDto {
    return true;
}

export function PagedResponsePostDtoFromJSON(json: any): PagedResponsePostDto {
    return PagedResponsePostDtoFromJSONTyped(json, false);
}

export function PagedResponsePostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedResponsePostDto {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(PostDtoFromJSON)),
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PagedResponsePostDtoToJSON(json: any): PagedResponsePostDto {
    return PagedResponsePostDtoToJSONTyped(json, false);
}

export function PagedResponsePostDtoToJSONTyped(value?: PagedResponsePostDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(PostDtoToJSON)),
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
    };
}

