/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { BookDto } from './BookDto';
import {
    BookDtoFromJSON,
    BookDtoFromJSONTyped,
    BookDtoToJSON,
    BookDtoToJSONTyped,
} from './BookDto';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageBookDto
 */
export interface PageBookDto {
    /**
     * 
     * @type {number}
     * @memberof PageBookDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageBookDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageBookDto
     */
    size?: number;
    /**
     * 
     * @type {Array<BookDto>}
     * @memberof PageBookDto
     */
    content?: Array<BookDto>;
    /**
     * 
     * @type {number}
     * @memberof PageBookDto
     */
    number?: number;
    /**
     * 
     * @type {Array<SortObject>}
     * @memberof PageBookDto
     */
    sort?: Array<SortObject>;
    /**
     * 
     * @type {boolean}
     * @memberof PageBookDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageBookDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageBookDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageBookDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageBookDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageBookDto interface.
 */
export function instanceOfPageBookDto(value: object): value is PageBookDto {
    return true;
}

export function PageBookDtoFromJSON(json: any): PageBookDto {
    return PageBookDtoFromJSONTyped(json, false);
}

export function PageBookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageBookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(BookDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageBookDtoToJSON(json: any): PageBookDto {
    return PageBookDtoToJSONTyped(json, false);
}

export function PageBookDtoToJSONTyped(value?: PageBookDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(BookDtoToJSON)),
        'number': value['number'],
        'sort': value['sort'],
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

