/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
    UserDtoToJSONTyped,
} from './UserDto';

/**
 * 
 * @export
 * @interface PageUserDto
 */
export interface PageUserDto {
    /**
     * 
     * @type {number}
     * @memberof PageUserDto
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUserDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageUserDto
     */
    size?: number;
    /**
     * 
     * @type {Array<UserDto>}
     * @memberof PageUserDto
     */
    content?: Array<UserDto>;
    /**
     * 
     * @type {number}
     * @memberof PageUserDto
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageUserDto
     */
    sort?: SortObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageUserDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageUserDto
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageUserDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageUserDto interface.
 */
export function instanceOfPageUserDto(value: object): value is PageUserDto {
    return true;
}

export function PageUserDtoFromJSON(json: any): PageUserDto {
    return PageUserDtoFromJSONTyped(json, false);
}

export function PageUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(UserDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageUserDtoToJSON(json: any): PageUserDto {
    return PageUserDtoToJSONTyped(json, false);
}

export function PageUserDtoToJSONTyped(value?: PageUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(UserDtoToJSON)),
        'number': value['number'],
        'sort': value['sort'] == null ? undefined : value['sort'],
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'empty': value['empty'],
    };
}

