/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeDto } from './RecipeDto';
import {
    RecipeDtoFromJSON,
    RecipeDtoFromJSONTyped,
    RecipeDtoToJSON,
    RecipeDtoToJSONTyped,
} from './RecipeDto';
import type { CommentDto } from './CommentDto';
import {
    CommentDtoFromJSON,
    CommentDtoFromJSONTyped,
    CommentDtoToJSON,
    CommentDtoToJSONTyped,
} from './CommentDto';

/**
 * 
 * @export
 * @interface PostDto
 */
export interface PostDto {
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    authorUsername?: string;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    authorEmail?: string;
    /**
     * 
     * @type {RecipeDto}
     * @memberof PostDto
     */
    recipe?: RecipeDto;
    /**
     * 
     * @type {Array<CommentDto>}
     * @memberof PostDto
     */
    comments?: Array<CommentDto>;
    /**
     * 
     * @type {Date}
     * @memberof PostDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof PostDto
     */
    imageUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostDto
     */
    authorIsFollowed?: boolean;
}

/**
 * Check if a given object implements the PostDto interface.
 */
export function instanceOfPostDto(value: object): value is PostDto {
    return true;
}

export function PostDtoFromJSON(json: any): PostDto {
    return PostDtoFromJSONTyped(json, false);
}

export function PostDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'authorUsername': json['authorUsername'] == null ? undefined : json['authorUsername'],
        'authorEmail': json['authorEmail'] == null ? undefined : json['authorEmail'],
        'recipe': json['recipe'] == null ? undefined : RecipeDtoFromJSON(json['recipe']),
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(CommentDtoFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
        'authorIsFollowed': json['authorIsFollowed'] == null ? undefined : json['authorIsFollowed'],
    };
}

export function PostDtoToJSON(json: any): PostDto {
    return PostDtoToJSONTyped(json, false);
}

export function PostDtoToJSONTyped(value?: Omit<PostDto, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authorUsername': value['authorUsername'],
        'authorEmail': value['authorEmail'],
        'recipe': RecipeDtoToJSON(value['recipe']),
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(CommentDtoToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'imageUrl': value['imageUrl'],
        'authorIsFollowed': value['authorIsFollowed'],
    };
}

