/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeDto
 */
export interface RecipeDto {
    /**
     * 
     * @type {string}
     * @memberof RecipeDto
     */
    readonly id?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeDto
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeDto
     */
    instructions?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeDto
     */
    ingredients?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeDto
     */
    authorName?: string;
    /**
     * 
     * @type {Date}
     * @memberof RecipeDto
     */
    createdAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof RecipeDto
     */
    isPosted?: boolean;
}

/**
 * Check if a given object implements the RecipeDto interface.
 */
export function instanceOfRecipeDto(value: object): value is RecipeDto {
    return true;
}

export function RecipeDtoFromJSON(json: any): RecipeDto {
    return RecipeDtoFromJSONTyped(json, false);
}

export function RecipeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'ingredients': json['ingredients'] == null ? undefined : json['ingredients'],
        'authorName': json['authorName'] == null ? undefined : json['authorName'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'isPosted': json['isPosted'] == null ? undefined : json['isPosted'],
    };
}

export function RecipeDtoToJSON(json: any): RecipeDto {
    return RecipeDtoToJSONTyped(json, false);
}

export function RecipeDtoToJSONTyped(value?: Omit<RecipeDto, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'instructions': value['instructions'],
        'ingredients': value['ingredients'],
        'authorName': value['authorName'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'isPosted': value['isPosted'],
    };
}

