/* tslint:disable */
/* eslint-disable */
/**
 * Authorization server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAddDto
 */
export interface UserAddDto {
    /**
     * 
     * @type {string}
     * @memberof UserAddDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddDto
     */
    password?: string;
}

/**
 * Check if a given object implements the UserAddDto interface.
 */
export function instanceOfUserAddDto(value: object): value is UserAddDto {
    return true;
}

export function UserAddDtoFromJSON(json: any): UserAddDto {
    return UserAddDtoFromJSONTyped(json, false);
}

export function UserAddDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAddDto {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserAddDtoToJSON(json: any): UserAddDto {
    return UserAddDtoToJSONTyped(json, false);
}

export function UserAddDtoToJSONTyped(value?: UserAddDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'email': value['email'],
        'password': value['password'],
    };
}

